---
title: Conan Adventures in Hot Springs Island 0
author: 'Will Bidstrup'
date: '2018-07-05'
slug: conan-adventures-in-hot-springs-island-0
categories:
  - RPG
tags:
  - before the game
---

I am excited to try out the Conan Adventures in An Age Undreamed Of RPG. It looks like a really well-designed system, oozing with Doom, Momentum and primal flavour.

As well, I am intrigued by the Hot Springs Island products. These define a system-neutral hex-crawling sandbox, set on a jungle island with two volcanoes.

Putting these two together seems like the greatest combination since ice-cream and chocolate sauce.  


# The setting

I place Hot Springs Island in Hyboria, specifically as one of the tropical islands near Argos and Zingara where pirates ply their trade. There are and were no Elves. Any evidence described as Elvish is instead remnants of an ancient Hyborian civilisation. 

# The Rules

I will be using the Conan Core Rule Book.  


# The Characters

I create three characters who will work as a team to find gold and glory in Hot Springs Island.  

Aracelle - an Argossean scoundrel, born into wealth that was lost in the petty squabbles between merchant families. She seeks fortune and fame.

Mirembe - a Kushite witch doctor, who joined a pirate ship to facilitate her travel to exotic lands. She trades healing powers and wisdom for access to lost and forbidden knowledge. She seeks knowledge and power.  

Eachann - a Bossonian mercenary


# The Objectives

Character objectives will be defined during play, but will be fairly standard Conan 

- Survival  
- Gaining treasure
- Uncovering secrets  


# Play notes
I’ll be running this in a slowplay style, with a focus on physical products and a classic atmosphere. 

I’ll be posting session reports in-between each episode of ‘carousing’, which is how the Conan system defines downtime.  

Each play report will contain two sections; the first will be narrative based and give snippets of action from the perspective of the characters in game; the second will be an analysis of the game including rules and design notes from the perspective of the Dungeon Master.  

*Note on spoilers* I’ll only be sharing information about Hot Springs Island that the characters encounter and figure out. I suspect they will die or retire somehow long before all of the secrets are revealed. But, if you want to ever play this adventure completely fresh, this series is probably not for you.

 


 