---
title: Slowplay - an approach to learning and playing RPGs
author: 'Will Bidstrup'
date: '2018-07-04'
slug: slowplay-an-approach-to-learning-relaxing-and-writing-with-tabletop-RPGs
categories:
  - RPG
tags:
  - articles
---

It has been mentioned many times that RPG enthusiasts will often spend much more time reading about games than actually playing them. This is certainly true for me, evidenced by the ever-growing collection of games I have, coupled with the ever-decreasing amount of time I am able to co-ordinate to run or play them. 

I also have a parallel interest in game design. So when I am reading an RPG product, my daydreaming is going in a few different directions; what would it be like to *play* this game, what would it be like to *run* this game, and *how was it designed*?  

Finally, although I certainly agree with the Lazy Duneon master approach for running games, I can see an alternate perspective as well - through really playing a game, the DM will certainly be in a good place to run it.  


So I am testing an approach I call “Slowplay” and it has three main ingredients;

1) Learn about new RPG systems by playing them solo - I mean as Dungeon Master and Player(s). 

2) Make the experience a tactile and relaxing one. Set up on a table with dice and paper. Put on thematic music. Make awesome characters. Savour each moment. Take notes.

3) Use the notes taken as prompts for writing, firstly from a narrative perspective from the game-world or player perspective, and secondly as the Dungeon Master or Game Designer.

All of the above requires a fair bit of imagination of course, but that’s what RPGs are all about.

EDIT: I thought there might be other people interested in this, and I was right. Time to [check out all of this](https://dieheart.net/solo-rpg-resources/).